name: Feature Test 2GP
on:
    push:
        branches:
            - feature/**
jobs:
    feature-test:
        name: "Feature Test 2GP"
        uses: MetechoDemo/standard-workflows/.github/workflows/feature-2gp.yml@main
        secrets:
            dev-hub-auth-url: "${{ secrets.DEV_HUB_AUTH_URL }}"